/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mdz_jpegtran_Transformation */

#ifndef _Included_org_mdz_jpegtran_Transformation
#define _Included_org_mdz_jpegtran_Transformation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mdz_jpegtran_Transformation
 * Method:    downscale
 * Signature: ([BLjava/nio/ByteBuffer;III)I
 */
JNIEXPORT jint JNICALL Java_org_mdz_jpegtran_Transformation_downscale
  (JNIEnv *, jclass, jbyteArray, jobject, jint, jint, jint);

/*
 * Class:     org_mdz_jpegtran_Transformation
 * Method:    crop
 * Signature: ([BLjava/nio/ByteBuffer;IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mdz_jpegtran_Transformation_crop
  (JNIEnv *, jclass, jbyteArray, jobject, jint, jint, jint, jint);

/*
 * Class:     org_mdz_jpegtran_Transformation
 * Method:    transpose
 * Signature: ([BLjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_mdz_jpegtran_Transformation_transpose
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     org_mdz_jpegtran_Transformation
 * Method:    transverse
 * Signature: ([BLjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_mdz_jpegtran_Transformation_transverse
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     org_mdz_jpegtran_Transformation
 * Method:    flip
 * Signature: ([BLjava/nio/ByteBuffer;Z)I
 */
JNIEXPORT jint JNICALL Java_org_mdz_jpegtran_Transformation_flip
  (JNIEnv *, jclass, jbyteArray, jobject, jboolean);

/*
 * Class:     org_mdz_jpegtran_Transformation
 * Method:    rotate
 * Signature: ([BLjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_mdz_jpegtran_Transformation_rotate
  (JNIEnv *, jclass, jbyteArray, jobject, jint);

/*
 * Class:     org_mdz_jpegtran_Transformation
 * Method:    getWidth
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_mdz_jpegtran_Transformation_getWidth
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_mdz_jpegtran_Transformation
 * Method:    getHeight
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_mdz_jpegtran_Transformation_getHeight
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
