# local/default
custom:
  iiif:
    image:
      maxWidth: 65500
      maxHeight: 65500
      canonicalRedirect: true

info:
  app:
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@maven.compiler.source@'
      target: '@maven.compiler.target@'
    project:
      artifactId: '@project.artifactId@'
      buildDetails: '@versionName@'
      groupId: '@project.groupId@'
      name: '@project.name@'
      version: '@project.version@'

javamelody:
  enabled: true
  init-parameters:
    allowed-addr-pattern: 'localhost|127\.0\.0\.1|0:0:0:0:0:0:0:1'
    authorized-users: 'admin:somepassword'
    http-transform-pattern: '(\\d+|(?<=currenttitles/).*|(?<=citationtitles/).*|(?<=occurrences/).*|(?<=periodical/).*|(?<=issues/).*)'
    # log http requests:
    log: false
    monitoring-path: '/monitoring/javamelody'
    url-exclude-pattern: '^(/webjars|/jsondoc|/monitoring).*'

management:
  endpoint:
    health:
      show-details: when-authorized
  endpoints:
    web:
      base-path: '/monitoring'
      exposure:
        include: '*'
  info:
    git:
      mode: full
  server:
    port: 9001

resourceRepository:
  resolved:
    patterns:
      # An image pattern resolving example:
      - pattern: ^(\d{8})_(\d{5})$
        substitutions:
          - 'file:/var/local/iiif/images/$1/original/image_$1_$2.tif'
          - 'file:/var/local/iiif/images/$1/300/image_$1_$2.jpg'
          - 'file:/var/local/iiif/images/$1/150/image_$1_$2.jpg'
      # An manifest pattern resolving example:
      - pattern: ^(\d{8})$
        substitutions:
          - 'file:/var/local/iiif/presentation/manifests/manifest_$1.json'
      # For the official IIIF Image API Validator
      - pattern: 67352ccc-d1b0-11e1-89ae-279075081939
        substitutions:
          - 'classpath:validation.jp2'
          - 'classpath:validation.png'
      # Collection manifests ('collection-' pattern-prefix is statically added to requested collection name to disambigued from other patterns)
      - pattern: ^collection-(.*)$
        substitutions:
          - 'file:/var/local/iiif/presentation/collections/$1.json'
      # Annotation list of transcriptions
      - pattern: ^transcription-(.*)$
        substitutions:
          - 'file:/var/local/iiif/presentation/annotations/$1.json'

server:
  error:
    include-exception: true
    include-stacktrace: always
  port: 9000
  server-header: "@project.name@ v@project.version@"

spring:
  messages:
    basename: 'messages, messages-commons'
    cache-duration: 5
    encoding: 'UTF-8'
    fallback-to-system-locale: false
  profiles:
    active: local
  security:
    user:
      name: admin
      password: secret
      roles: ACTUATOR
  thymeleaf:
    cache: false
    mode: HTML

---

# PROD
server:
  error:
    include-exception: false
    include-stacktrace: 'never'

spring:
  profiles: PROD
  thymeleaf:
    cache: true
